
GET http://localhost:5021/games
 
###
GET http://localhost:5021/games/12

###
POST http://localhost:5021/games
Content-Type: application/json

{
   "name":"Super Mario",
    "genreid": 3,
    "price" : 12.17,
    "releaseDate":"2023-12-06"
}

###
PUT http://localhost:5021/games/3
Content-Type: application/json

  {
    "name": "Street Fighter II Turbo",
    "genreId": 1,
    "price": 19.99,
    "releaseDate": "1991-02-01"
  }
###
DELETE http://localhost:5021/games/13